# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hiddensqli.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10hiddensqli.proto\x12\x0bhidden.sqli\":\n\rSearchRequest\x12\x13\n\x0bsearch_word\x18\x01 \x01(\t\x12\x14\n\x0chidden_param\x18\x02 \x01(\t\"1\n\x13SearchHiddenRequest\x12\x1a\n\x12search_hidden_word\x18\x01 \x01(\t\" \n\x0eSearchResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2O\n\x08Searcher\x12\x43\n\x06Search\x12\x1a.hidden.sqli.SearchRequest\x1a\x1b.hidden.sqli.SearchResponse\"\x00\x32\\\n\x0eHiddenSearcher\x12J\n\x07Search2\x12 .hidden.sqli.SearchHiddenRequest\x1a\x1b.hidden.sqli.SearchResponse\"\x00\x42,\n\x11xenon.hidden.sqliB\x0fHiddenSqliProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hiddensqli_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021xenon.hidden.sqliB\017HiddenSqliProtoP\001\242\002\003HLW'
  _globals['_SEARCHREQUEST']._serialized_start=33
  _globals['_SEARCHREQUEST']._serialized_end=91
  _globals['_SEARCHHIDDENREQUEST']._serialized_start=93
  _globals['_SEARCHHIDDENREQUEST']._serialized_end=142
  _globals['_SEARCHRESPONSE']._serialized_start=144
  _globals['_SEARCHRESPONSE']._serialized_end=176
  _globals['_SEARCHER']._serialized_start=178
  _globals['_SEARCHER']._serialized_end=257
  _globals['_HIDDENSEARCHER']._serialized_start=259
  _globals['_HIDDENSEARCHER']._serialized_end=351
# @@protoc_insertion_point(module_scope)
