# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import hiddensqli_pb2 as hiddensqli__pb2


class SearcherStub(object):
    """The Searcher service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
                '/hidden.sqli.Searcher/Search',
                request_serializer=hiddensqli__pb2.SearchRequest.SerializeToString,
                response_deserializer=hiddensqli__pb2.SearchResponse.FromString,
                )


class SearcherServicer(object):
    """The Searcher service definition.
    """

    def Search(self, request, context):
        """Sends a Search Query
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearcherServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=hiddensqli__pb2.SearchRequest.FromString,
                    response_serializer=hiddensqli__pb2.SearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hidden.sqli.Searcher', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Searcher(object):
    """The Searcher service definition.
    """

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hidden.sqli.Searcher/Search',
            hiddensqli__pb2.SearchRequest.SerializeToString,
            hiddensqli__pb2.SearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class HiddenSearcherStub(object):
    """The Searcher service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search2 = channel.unary_unary(
                '/hidden.sqli.HiddenSearcher/Search2',
                request_serializer=hiddensqli__pb2.SearchHiddenRequest.SerializeToString,
                response_deserializer=hiddensqli__pb2.SearchResponse.FromString,
                )


class HiddenSearcherServicer(object):
    """The Searcher service definition.
    """

    def Search2(self, request, context):
        """Sends a Search Query
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HiddenSearcherServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Search2': grpc.unary_unary_rpc_method_handler(
                    servicer.Search2,
                    request_deserializer=hiddensqli__pb2.SearchHiddenRequest.FromString,
                    response_serializer=hiddensqli__pb2.SearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hidden.sqli.HiddenSearcher', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HiddenSearcher(object):
    """The Searcher service definition.
    """

    @staticmethod
    def Search2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hidden.sqli.HiddenSearcher/Search2',
            hiddensqli__pb2.SearchHiddenRequest.SerializeToString,
            hiddensqli__pb2.SearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
