/**
 * @fileoverview gRPC-Web generated client stub for hidden.sqli
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.12.4
// source: hiddensqli.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.hidden = {};
proto.hidden.sqli = require('./hiddensqli_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.hidden.sqli.SearcherClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.hidden.sqli.SearcherPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hidden.sqli.SearchRequest,
 *   !proto.hidden.sqli.SearchResponse>}
 */
const methodDescriptor_Searcher_Search = new grpc.web.MethodDescriptor(
  '/hidden.sqli.Searcher/Search',
  grpc.web.MethodType.UNARY,
  proto.hidden.sqli.SearchRequest,
  proto.hidden.sqli.SearchResponse,
  /**
   * @param {!proto.hidden.sqli.SearchRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.hidden.sqli.SearchResponse.deserializeBinary
);


/**
 * @param {!proto.hidden.sqli.SearchRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.hidden.sqli.SearchResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.hidden.sqli.SearchResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.hidden.sqli.SearcherClient.prototype.search =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/hidden.sqli.Searcher/Search',
      request,
      metadata || {},
      methodDescriptor_Searcher_Search,
      callback);
};


/**
 * @param {!proto.hidden.sqli.SearchRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.hidden.sqli.SearchResponse>}
 *     Promise that resolves to the response
 */
proto.hidden.sqli.SearcherPromiseClient.prototype.search =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/hidden.sqli.Searcher/Search',
      request,
      metadata || {},
      methodDescriptor_Searcher_Search);
};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.hidden.sqli.HiddenSearcherClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.hidden.sqli.HiddenSearcherPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hidden.sqli.SearchHiddenRequest,
 *   !proto.hidden.sqli.SearchResponse>}
 */
const methodDescriptor_HiddenSearcher_Search2 = new grpc.web.MethodDescriptor(
  '/hidden.sqli.HiddenSearcher/Search2',
  grpc.web.MethodType.UNARY,
  proto.hidden.sqli.SearchHiddenRequest,
  proto.hidden.sqli.SearchResponse,
  /**
   * @param {!proto.hidden.sqli.SearchHiddenRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.hidden.sqli.SearchResponse.deserializeBinary
);


/**
 * @param {!proto.hidden.sqli.SearchHiddenRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.hidden.sqli.SearchResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.hidden.sqli.SearchResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.hidden.sqli.HiddenSearcherClient.prototype.search2 =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/hidden.sqli.HiddenSearcher/Search2',
      request,
      metadata || {},
      methodDescriptor_HiddenSearcher_Search2,
      callback);
};


/**
 * @param {!proto.hidden.sqli.SearchHiddenRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.hidden.sqli.SearchResponse>}
 *     Promise that resolves to the response
 */
proto.hidden.sqli.HiddenSearcherPromiseClient.prototype.search2 =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/hidden.sqli.HiddenSearcher/Search2',
      request,
      metadata || {},
      methodDescriptor_HiddenSearcher_Search2);
};


module.exports = proto.hidden.sqli;

